// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// logisticMH
arma::mat logisticMH(arma::mat data, arma::vec nsamples, arma::vec ini_pars, arma::mat priors, int niter, double scale, int nadapt, int nprintsum, double maxscale, double niterdim, int nrand, List randindexesL, arma::imat data_rand);
RcppExport SEXP BayesLog_logisticMH(SEXP dataSEXP, SEXP nsamplesSEXP, SEXP ini_parsSEXP, SEXP priorsSEXP, SEXP niterSEXP, SEXP scaleSEXP, SEXP nadaptSEXP, SEXP nprintsumSEXP, SEXP maxscaleSEXP, SEXP niterdimSEXP, SEXP nrandSEXP, SEXP randindexesLSEXP, SEXP data_randSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ini_pars(ini_parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type nadapt(nadaptSEXP);
    Rcpp::traits::input_parameter< int >::type nprintsum(nprintsumSEXP);
    Rcpp::traits::input_parameter< double >::type maxscale(maxscaleSEXP);
    Rcpp::traits::input_parameter< double >::type niterdim(niterdimSEXP);
    Rcpp::traits::input_parameter< int >::type nrand(nrandSEXP);
    Rcpp::traits::input_parameter< List >::type randindexesL(randindexesLSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type data_rand(data_randSEXP);
    __result = Rcpp::wrap(logisticMH(data, nsamples, ini_pars, priors, niter, scale, nadapt, nprintsum, maxscale, niterdim, nrand, randindexesL, data_rand));
    return __result;
END_RCPP
}
